name: Tests

on:
  - push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests
          python -m pip install --upgrade pip
          pip install pytest-playwright
          pip install Scrapy


      - name: Ensure browsers are installed
        run: python -m playwright install chromium --with-deps

      - name: Run tests
        run: |
          python -m http.server 8000 &
          pytest -v
          scrapy runspider tests/parsing.py

      - name: Send Telegram message
        run: python send_message.py
        env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}

